version: '2'
services:
  db:
    restart: always
    image: postgres
  redis:
    restart: always
    image: redis
  web:
    restart: always
    build: .
    env_file: .env.production
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - ./public/assets:/mastodon/public/assets
      - ./public/system:/mastodon/public/system
  sidekiq:
    restart: always
    build: .
    env_file: .env.production
    command: bundle exec sidekiq -q default -q mailers -q push
    depends_on:
      - db
      - redis
    volumes:
      - ./public/system:/mastodon/public/system
